In [1]:
import numpy as np
import pandas as pd

In [98]:
## Numpy ##

In [2]:
np.array([1,2,3,45,6])

array([ 1,  2,  3, 45,  6])

In [3]:
np.ones((3,5),dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
x=np.arange(0,20,2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.random.random((3,3))

array([[0.55860489, 0.7225977 , 0.59670642],
       [0.04128806, 0.30846855, 0.96768949],
       [0.34001334, 0.342865  , 0.18329894]])

In [18]:
np.random.normal(0,10,(3,3))

array([[ -3.8586568 ,  -5.36422319,  -6.65219509],
       [-13.14085765,  -5.55240271,  -4.09639092],
       [-20.31769837, -12.10126787,   3.97357045]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
x1=np.random.randint(10,size=6)
x1

array([9, 5, 3, 4, 0, 8])

In [23]:
x2=np.random.randint(10,size=(3,4))
x2

array([[8, 4, 3, 3],
       [6, 9, 7, 7],
       [4, 0, 4, 7]])

In [24]:
x3=np.random.randint(10,size=(3,4,5))
x3

array([[[4, 6, 8, 8, 7],
        [9, 6, 2, 3, 0],
        [0, 5, 6, 4, 6],
        [0, 8, 5, 0, 0]],

       [[1, 4, 7, 2, 2],
        [5, 9, 7, 0, 1],
        [9, 6, 7, 4, 1],
        [1, 2, 3, 3, 0]],

       [[7, 0, 5, 8, 7],
        [6, 6, 0, 7, 6],
        [4, 6, 5, 5, 3],
        [5, 2, 6, 5, 3]]])

In [25]:
print("X3 ndim",x3.ndim)
print("X2 size",x2.size)
print("X1 shape",x1.shape)

X3 ndim 3
X2 size 12
X1 shape (6,)


In [28]:
x1=np.array([0.,5,3,7,9,9.6])
x1[4]

9.0

In [33]:
x1[-1]

8

In [34]:
x1=np.arange(0,20,2)
x1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
print(x1[:5])
print(x1[::2])
print(x1[5:])


[0 2 4 6 8]
[ 0  4  8 12 16]
[10 12 14 16 18]


In [41]:
x2=np.random.normal(10,size=(3,3))
x2

array([[ 9.87893981,  9.09270799,  9.81895483],
       [ 8.69924156, 10.43813448,  9.52730069],
       [ 9.46763853,  8.93258581, 11.84548822]])

In [42]:
x2[:2,:3]

array([[ 9.87893981,  9.09270799,  9.81895483],
       [ 8.69924156, 10.43813448,  9.52730069]])

In [44]:
x2_copy=x2.copy()
x2_copy

array([[ 9.87893981,  9.09270799,  9.81895483],
       [ 8.69924156, 10.43813448,  9.52730069],
       [ 9.46763853,  8.93258581, 11.84548822]])

In [49]:
x1=np.random.randint(5,size =4)
x2=np.random.randint(10,size = 5)
x3=np.random.randint(8,size=6)
print(x1,x2,x3)

[2 0 1 2] [1 9 2 9 2] [4 5 5 3 4 7]


In [52]:
z = np.concatenate([x1,x2,x3])
z

array([2, 0, 1, 2, 1, 9, 2, 9, 2, 4, 5, 5, 3, 4, 7])

In [55]:
w = np.split(z,(4,5))
w

[array([2, 0, 1, 2]), array([1]), array([9, 2, 9, 2, 4, 5, 5, 3, 4, 7])]

In [56]:
theta = np.linspace(0,np.pi,3)

In [57]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [58]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [59]:
np.arcsin(theta)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24856\458218287.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(theta)


array([ 0., nan, nan])

In [61]:
x=np.arange(10)
np.log(x)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24856\4197220341.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [66]:
x = np.random.randint(10,size=4)
x

array([7, 0, 7, 6])

In [67]:
from scipy import special

In [69]:
special.gamma(x)


array([720.,  inf, 720., 120.])

In [73]:
special.erfc(x)


array([4.18382561e-23, 1.00000000e+00, 4.18382561e-23, 2.15197367e-17])

In [75]:
special.erfinv(x)

array([nan,  0., nan, nan])

In [76]:
np.sum(x)


20

In [87]:
q=np.prod(x)
w=np.mean(x)
r=np.var(x)
t=np.max(x)
y=np.argmax(x)
v=np.array([q,w,r,t,y])
v

array([0. , 5. , 8.5, 7. , 0. ])

In [88]:
x=np.random.randint(5,size=6)
x

array([0, 2, 3, 4, 1, 3])

In [89]:
np.sort(x)


array([0, 1, 2, 3, 3, 4])

In [90]:
np.argsort(x)

array([0, 4, 1, 2, 5, 3], dtype=int64)

In [96]:
k=np.random.randint(5,100,(5,6))
np.sort(k,axis=0)

array([[56,  5, 16, 54, 44,  5],
       [56, 28, 69, 62, 73, 29],
       [63, 51, 80, 63, 73, 32],
       [65, 69, 89, 81, 76, 73],
       [65, 89, 91, 95, 86, 78]])

In [97]:
np.sort(k,axis=1)

array([[28, 44, 54, 56, 78, 80],
       [ 5,  5, 56, 63, 76, 91],
       [29, 62, 65, 69, 86, 89],
       [16, 32, 51, 65, 73, 95],
       [63, 69, 73, 73, 81, 89]])

In [ ]:
### Pandas ###

In [106]:
import pandas as pd
import numpy as np

data = pd.Series(np.random.randint(5, size=6), index=['a', 'b', 'c', 'd', 'e', 'f'])
data

a    0
b    2
c    0
d    1
e    1
f    4
dtype: int32

In [121]:
import pandas as pd

data = {
    'City': ['Mumbai', 'Delhi', 'Bangalore', 'Kolkata', 'Chennai'],
    'Population (Millions)': [12.48, 11.02, 8.52, 4.58, 4.34],
    'area (Kilometers) ':[500000,100000,200000,300000,450000]
}

indian_cities_df = pd.DataFrame(data)
indian_cities_df

City  Population (Millions)  area (Kilometers) 
0     Mumbai                  12.48              500000
1      Delhi                  11.02              100000
2  Bangalore                   8.52              200000
3    Kolkata                   4.58              300000
4    Chennai                   4.34              450000

In [117]:
indian_cities_df.City

0       Mumbai
1        Delhi
2    Bangalore
3      Kolkata
4      Chennai
Name: City, dtype: object

In [114]:
indian_cities_df.columns

Index(['City', 'Population (Millions)'], dtype='object')

In [128]:
indian_cities_df['area (Kilometers) ']

0    500000
1    100000
2    200000
3    300000
4    450000
Name: area (Kilometers) , dtype: int64

In [131]:
indian_cities_df['density'] = indian_cities_df['Population (Millions)']/indian_cities_df['area (Kilometers) ']
indian_cities_df['density']

0    0.000025
1    0.000110
2    0.000043
3    0.000015
4    0.000010
Name: density, dtype: float64

In [132]:
indian_cities_df

City  Population (Millions)  area (Kilometers)    density
0     Mumbai                  12.48              500000  0.000025
1      Delhi                  11.02              100000  0.000110
2  Bangalore                   8.52              200000  0.000043
3    Kolkata                   4.58              300000  0.000015
4    Chennai                   4.34              450000  0.000010

In [133]:
indian_cities_df.T

0        1          2         3        4
City                     Mumbai    Delhi  Bangalore   Kolkata  Chennai
Population (Millions)     12.48    11.02       8.52      4.58     4.34
area (Kilometers)        500000   100000     200000    300000   450000
density                0.000025  0.00011   0.000043  0.000015  0.00001

In [134]:
indian_cities_df.iloc[1:3]

City  Population (Millions)  area (Kilometers)    density
1      Delhi                  11.02              100000  0.000110
2  Bangalore                   8.52              200000  0.000043

In [135]:
indian_cities_df.loc[1:3]


City  Population (Millions)  area (Kilometers)    density
1      Delhi                  11.02              100000  0.000110
2  Bangalore                   8.52              200000  0.000043
3    Kolkata                   4.58              300000  0.000015

In [138]:
indian_cities_df.isnull()

City  Population (Millions)  area (Kilometers)   density
0  False                  False               False    False
1  False                  False               False    False
2  False                  False               False    False
3  False                  False               False    False
4  False                  False               False    False

In [140]:
indian_cities_df.isnull().sum()

City                     0
Population (Millions)    0
area (Kilometers)        0
density                  0
dtype: int64

In [141]:
indian_cities_df.dropna()

City  Population (Millions)  area (Kilometers)    density
0     Mumbai                  12.48              500000  0.000025
1      Delhi                  11.02              100000  0.000110
2  Bangalore                   8.52              200000  0.000043
3    Kolkata                   4.58              300000  0.000015
4    Chennai                   4.34              450000  0.000010

In [142]:
indian_cities_df.fillna(method='ffill')

City  Population (Millions)  area (Kilometers)    density
0     Mumbai                  12.48              500000  0.000025
1      Delhi                  11.02              100000  0.000110
2  Bangalore                   8.52              200000  0.000043
3    Kolkata                   4.58              300000  0.000015
4    Chennai                   4.34              450000  0.000010

In [143]:
indian_cities_df.describe()

Population (Millions)  area (Kilometers)    density
count                5.00000            5.000000  5.000000
mean                 8.18800       310000.000000  0.000041
std                  3.68702       167332.005307  0.000041
min                  4.34000       100000.000000  0.000010
25%                  4.58000       200000.000000  0.000015
50%                  8.52000       300000.000000  0.000025
75%                 11.02000       450000.000000  0.000043
max                 12.48000       500000.000000  0.000110

In [144]:
indian_cities_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   City                   5 non-null      object 
 1   Population (Millions)  5 non-null      float64
 2   area (Kilometers)      5 non-null      int64  
 3   density                5 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 288.0+ bytes


In [145]:
indian_cities_df.head()

City  Population (Millions)  area (Kilometers)    density
0     Mumbai                  12.48              500000  0.000025
1      Delhi                  11.02              100000  0.000110
2  Bangalore                   8.52              200000  0.000043
3    Kolkata                   4.58              300000  0.000015
4    Chennai                   4.34              450000  0.000010

In [146]:
indian_cities_df.tail()

City  Population (Millions)  area (Kilometers)    density
0     Mumbai                  12.48              500000  0.000025
1      Delhi                  11.02              100000  0.000110
2  Bangalore                   8.52              200000  0.000043
3    Kolkata                   4.58              300000  0.000015
4    Chennai                   4.34              450000  0.000010

In [147]:
indian_cities_df.shape

(5, 4)

In [148]:
indian_cities_df.dtypes

City                      object
Population (Millions)    float64
area (Kilometers)          int64
density                  float64
dtype: object

In [150]:
indian_cities_df.items()

<generator object DataFrame.items at 0x000002827FD99E70>

In [151]:
indian_cities_df.keys()

Index(['City', 'Population (Millions)', 'area (Kilometers) ', 'density'], dtype='object')

In [152]:
indian_cities_df.notnull()

City  Population (Millions)  area (Kilometers)   density
0  True                   True                True     True
1  True                   True                True     True
2  True                   True                True     True
3  True                   True                True     True
4  True                   True                True     True